export const tenants = [
    {
        tenantID: 0,
        name: "Sjoerd",
        age: 26,
        occupation: "Webdeveloper",
        company: "Codaisseur",
        incomePerMonth: 2500,
        url: ["https://images.pexels.com/photos/462680/pexels-photo-462680.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"],
        like: [],
        dislike: [],
        thinking: [],
        lastOwnerIDSeen: 2
    },
    {
        tenantID: 1,
        name: "Abi",
        age: 29,
        occupation: "Dentist",
        company: "Abi's tooth repair shop",
        incomePerMonth: 5000,
        url: ["https://images.pexels.com/photos/712521/pexels-photo-712521.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"],
        like: [],
        dislike: [],
        thinking: [],
        lastOwnerIDSeen: 0
    },
    {
        tenantID: 2,
        name: "Mohammad",
        age: 30,
        occupation: "Astronaut",
        company: "NASA",
        incomePerMonth: 4000,
        url: ["https://images.pexels.com/photos/33684/astronaut-spacewalk-iss-tools.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"],
        like: [],
        dislike: [],
        thinking: [],
        lastOwnerIDSeen: 0
    },
    {
        tenantID: 3,
        name: "John",
        age: 20,
        occupation: "Unemployed",
        company: "Social Welfare",
        incomePerMonth: 1000,
        url: ["https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"],
        like: [],
        dislike: [],
        thinking: [],
        lastOwnerIDSeen: 0
    },
    {
        tenantID: 4,
        name: "Lisa",
        age: 50,
        occupation: "Farmer",
        company: "Self Employed",
        incomePerMonth: 3500,
        url: ["https://images.pexels.com/photos/324658/pexels-photo-324658.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"],
        like: [],
        dislike: [],
        thinking: [],
        lastOwnerIDSeen: 0
    },
    {
        tenantID: 5,
        name: "Roger",
        age: 55,
        occupation: "Singer & Songwriter",
        company: "Self Employed",
        incomePerMonth: 2500,
        url: ["https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"],
        like: [],
        dislike: [],
        thinking: [],
        lastOwnerIDSeen: 0
    },
    {
        tenantID: 6,
        name: "Evelyn",
        age: 25,
        occupation: "Lawyer",
        company: "Baker McKenzie",
        incomePerMonth: 4500,
        url: ["https://images.pexels.com/photos/713312/pexels-photo-713312.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"],
        like: [],
        dislike: [],
        thinking: [],
        lastOwnerIDSeen: 0
    },
    {
        tenantID: 7,
        name: "Lisa",
        age: 29,
        occupation: "Bitcoin Expert",
        company: "John McAfee",
        incomePerMonth: 35000,
        url: ["https://images.pexels.com/photos/1037915/pexels-photo-1037915.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"],
        like: [],
        dislike: [],
        thinking: [],
        lastOwnerIDSeen: 0
    }    
]